server:
  port: 8088
spring:
  datasource:
    username: root
    password: fuhongze
    url: jdbc:mysql://localhost:3306/ssm
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.fhz.entity
  mapper-locations: mapper/*Mapper.xml